apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-hello-world-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-hello-world
  template:
    metadata:
      labels:
        app: php-hello-world
    spec:
      containers:
      - name: php-hello-world
        image: obemecher/test:latest
        ports:
        - containerPort: 32777

