apiVersion: v1
kind: Service
metadata:
  name: php-hello-world-service
spec:
  type: NodePort
  selector:
    app: php-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 32777
      nodePort: 30001

